### ISSUE TITLE
When leaving a chat, an error is thrown by handleNewMessage

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1249]
```
I/flutter (14974): Caught error: setState() or markNeedsBuild() called during build.
I/flutter (14974): This MessagesView widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter (14974): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (14974):   MessagesView-[<'iMessage;-;+14106930456'>]
I/flutter (14974): The widget which was currently being built when the offending call was made was:
```

**Comment by zlshames** [comment]
Full stacktrace:
```
I/flutter (14974): #39     MultiChildLayoutDelegate._callPerformLayout
package:flutter/…/rendering/custom_layout.dart:240
I/flutter (14974): #40     RenderCustomMultiChildLayoutBox.performLayout
package:flutter/…/rendering/custom_layout.dart:404
I/flutter (14974): #41     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1636
I/flutter (14974): #42     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:881
I/flutter (14974): #43     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:462
I/flutter (14974): #44     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:876
I/flutter (14974): #45     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:328
I/flutter (14974): #46     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
I/flutter (14974): #47     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
I/flutter (14974): #48     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
I/flutter (14974): #49     _rootRun (dart:async/zone.dart:1354:13)
I/flutter (14974): #50     _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (14974): #51     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (14974): #52     _invoke (dart:ui/hooks.dart:163:10)
I/flutter (14974): #53     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
I/flutter (14974): #54     _drawFrame (dart:ui/hooks.dart:126:31)
I/flutter (14974):

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5033 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was
SecureGate
lib\main.dart:181I/flutter (14974): #39     MultiChildLayoutDelegate._callPerformLayout
package:flutter/…/rendering/custom_layout.dart:240
I/flutter (14974): #40     RenderCustomMultiChildLayoutBox.performLayout
package:flutter/…/rendering/custom_layout.dart:404
I/flutter (14974): #41     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1636
I/flutter (14974): #42     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:881
I/flutter (14974): #43     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:462
I/flutter (14974): #44     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:876
I/flutter (14974): #45     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:328
I/flutter (14974): #46     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
I/flutter (14974): #47     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
I/flutter (14974): #48     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
I/flutter (14974): #49     _rootRun (dart:async/zone.dart:1354:13)
I/flutter (14974): #50     _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (14974): #51     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (14974): #52     _invoke (dart:ui/hooks.dart:163:10)
I/flutter (14974): #53     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
I/flutter (14974): #54     _drawFrame (dart:ui/hooks.dart:126:31)
I/flutter (14974):

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5033 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was
SecureGate
lib\main.dart:181
```

**Comment by tneotia** [comment]
Can't reproduce this one

**Comment by zlshames** [comment]
Might have been a one off. Leaving open for a bit to confirm
