### ISSUE TITLE
Rx Stream seems to error after downloading an attachment

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1250]
```
I/flutter (14974): Finished fetching attachment
I/flutter (14974): Attachment downloaded in 2926 ms
I/flutter (14974): Caught error: Null check operator used on a null value
I/flutter (14974): #0      GetStream.removeSubscription
package:get/…/rx_stream/get_stream.dart:22
I/flutter (14974): #1      LightSubscription.cancel
package:get/…/rx_stream/get_stream.dart:148
I/flutter (14974): #2      NotifyManager.close.<anonymous closure>
package:get/…/rx_core/rx_impl.dart:163
I/flutter (14974): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
I/flutter (14974): #4      NotifyManager.close
package:get/…/rx_core/rx_impl.dart:161
I/flutter (14974): #5      _ObxState.dispose
package:get/…/rx_flutter/rx_obx_widget.dart:48
I/flutter (14974): #6      StatefulElement.unmount
package:flutter/…/widgets/framework.dart:4800
I/flutter (14974): #7      _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1847
I/flutter (14974): #8      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (14974): #9      _InactiveElements._unmountAll
package:flutter/…/widgets/framework.dart:1856
I/flutter (14974): #10     BuildOwner.finalizeTree.<anonymous closure>
package:flutter/…/widgets/framework.dart:2840
I/flutter (14974): #11     BuildOwner.lockState
package:flutter/…/widgets/framework.dart:2473
I/flutter (14974): #12     BuildOwner.finalizeTree
package:flutter/…/widgets/framework.dart:2839
I/flutter (14974): #13     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:877
I/flutter (14974): #14     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:328
I/flutter (14974): #15     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
I/flutter (14974): #16     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
I/flutter (14974): #17     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
I/flutter (14974): #18     _rootRun (dart:async/zone.dart:1354:13)
I/flutter (14974): #19     _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (14974): #20     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (14974): #21     _invoke (dart:ui/hooks.dart:163:10)
I/flutter (14974): #22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
I/flutter (14974): #23     _drawFrame (dart:ui/hooks.dart:126:31)
I/flutter (14974):
W/System  (14974): A resource failed to call close.
```

**Comment by tneotia** [comment]
Internal GetX error, we have to wait for a new version as confirmed in their Discord

**Comment by zlshames** [comment]
Closing as it's waiting on a GetX update
