### ISSUE TITLE
Crash when inserting bitmoji

### ISSUE THREAD

**Issue by Bricktheworld** [BlueBubblesApp/BlueBubbles-Android-App#298]
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
    at io.flutter.plugin.editing.InputConnectionAdaptor.commitContent(InputConnectionAdaptor.java:519)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:566)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8154)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

The fix will require a full rebuild of the flutter engine

**Comment by CSab6482** [comment]
Closed?

**Comment by zlshames** [comment]
Closed :)
