### ISSUE TITLE
Opening fullscreen camera/video doesn't work on first attempt

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#597]
Leaving the chat and going into another one fixes the issue

**Comment by zlshames** [comment]
Can you please get a video of this? I'm having a hard time reproducing it

**Comment by CSab6482** [comment]
https://streamable.com/j5wwbm
Here it is on a demo server, unfortunately on this test I wasn't able to get the full screen camera to work at all

**Comment by cynical89** [comment]
On opening the full screen camera.
```
E/flutter (10953): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot create file, path = '/data/user/0/com.bluebubbles.messaging/files/attachments/dfndsgiYhv^`^fZZ.png' (OS Error: No such file or directory, errno = 2)
E/flutter (10953): #0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
E/flutter (10953): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10953): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10953): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (10953): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (10953): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (10953): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (10953): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (10953): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10953): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10953): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10953): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10953): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10953): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10953): 
```

On Opening the video recorder.
```
E/flutter (10953): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot create file, path = '/data/user/0/com.bluebubbles.messaging/files/attachments/pjo`pi_qq[k_sjyy.mp4' (OS Error: No such file or directory, errno = 2)
E/flutter (10953): #0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
E/flutter (10953): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10953): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10953): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (10953): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (10953): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (10953): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (10953): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (10953): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10953): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10953): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10953): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10953): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10953): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10953): 
```

**Comment by cynical89** [comment]
The issue is that the attachments directory is not being created before the camera is being opened. There are 3 temporary solutions to this issue

1) Have someone send you an attachment,
2) Send a picture from your gallery
3) Open another conversation which contains an attachment.

This is why sometimes you can just change conversations and it will allow you to use the camera/video player and sometimes it won't.

**Comment by zlshames** [comment]
Great find! I think we just need to make a check before hand to make sure the attachments directory is created. Should be a quick fix
